# Docker Hub: conchoid/dependency-check:v12.2.0-2-trixie-arm64
FROM debian:trixie-slim

# Preset locale to en_US.UTF-8 and install common tools
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
       locales \
       git \
       ssh \
       connect-proxy \
       curl \
       ca-certificates \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && rm -rf /etc/ssh/ssh_host_*_key \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=conchoid/debian:trixie-slim-arm64 /usr/local/bin/git-lfs /usr/local/bin/git-lfs
RUN git lfs install

ENV LANG=en_US.utf8

ENV SETUP_HOME=/opt/dependencycheck

ENV CURL_RETRY_OPT='--retry 3 --max-time 180 --retry-max-time 300'
ENV JVM_PATH=/opt/java/openjdk
RUN mkdir -p ${JVM_PATH}

# Install openjdk11 (Eclipse Temurin)
RUN cd ${JVM_PATH} \
    && curl $CURL_RETRY_OPT -OL "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.31%2B11/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.31_11.tar.gz" \
    && echo "257f4d39e060658fc2eb89a803ca43b3f337e64e253f2d94ebae1d85c9ef5f69 OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.31_11.tar.gz" | sha256sum -c - \
    && tar zxf "OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.31_11.tar.gz" -C ${JVM_PATH} \
    && rm "OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.31_11.tar.gz"

ENV JAVA_HOME=${JVM_PATH}/jdk-11.0.31+11
ENV JENV_ROOT=/opt/jenv
ENV PATH="${JENV_ROOT}/shims:${JENV_ROOT}/bin:$JAVA_HOME/bin:$PATH"

COPY ./setup.sh $SETUP_HOME/
RUN $SETUP_HOME/setup.sh $SETUP_HOME && rm -f $SETUP_HOME/setup.sh
